import time
from ircodec.command import CommandSet
controller = CommandSet(emitter_gpio=4, receiver_gpio=14, name='Room AC Controller')
print("Let's create a remote controller for you room AC")
print("Push ON button")
controller.add('ON')
print("Push OFF button")
controller.add('OFF')
print("Push MODE button")
controller.add('MODE')
print("Push TEMP-UP button")
controller.add('TEMP-UP')
print("Push TEMP-DOWN button")
controller.add('TEMP-DOWN')
print("Push SPEED-UP button")
controller.add('SPEED-UP')
print("Push SPEED-DOWN button")
controller.add('SPEED-DOWn')
print("Done, thank you")
controller.save_as('Room_AC.json')
